### ISSUE TITLE
Address PMC requirements

### ISSUE THREAD

**Issue by m0mus** [jakartaee/messaging#188]
All EE4J projects must follow the requirements described here:
https://www.eclipse.org/ee4j/news/

**Comment by keilw** [comment]
It's more complicated here, see https://github.com/eclipse-ee4j/jms-api/issues/185, but assuming EE4J_8 is the Java EE 8 baseline, then the project lead is supposed to bring the 2.0a folder into that release, while master branch is for the 2.1 folder (meant for the next release)

**Comment by keilw** [comment]
Not that I could see. The "requirements" are now called "direction" and found under https://www.eclipse.org/ee4j/direction.php. 

I could not even see it mention the branches, but following what other projects did, IMO the 2.0a folder should become an "EE4J_8" branch or whatever the name is in the other cases. And 2.1 should be the baseline for master.

**Comment by m0mus** [comment]
Yes, I see, the URL is changed because of the web site redesign. I found it here: https://www.eclipse.org/ee4j/news/?date=2018-02-16

@waynebeaton can we have a proper permalink for this document?

**Comment by keilw** [comment]
I created separate branches, I am able to do that, but e.g. enforcing review can only be done by the repo owner AFAIK.

There seems to be a mismatch between both
https://github.com/javaee/jms-spec/blob/master/jms2.0.1/pom.xml
or
https://github.com/javaee/jms-spec/tree/master/jms2.0a
(the latter was used as 2.0 Final here) 

and the MavenCentral deployment of JMS 2.0.1:
https://search.maven.org/artifact/javax.jms/javax.jms-api/2.0.1/jar

The POMs look substantially different, not sure, where it came from, especially the artifactIds just did not match here. Whether or not the sources (moved into the EE4J_8 branch) are also different from JMS 2.0.1 I cannot say for sure. @m0mus, @nigeldeakin do you have any chance to compare them and see, if the EE4J_8 branch (formely jms2.0a folder) is what was in Java EE 8?

**Comment by nigeldeakin** [comment]
Essentially, the jars on Maven Central are considered to be part of the RI, not the specification, and released as part of the RI (GlassFish MQ), using 
https://github.com/javaee/openmq/blob/master/mq/main/javax-jms/pom.xml

The poms in https://github.com/javaee/jms-spec were only used to build the javadocs.

**Comment by keilw** [comment]
So as 2.0.1 has already been published, would you say the EE4J_8 branch (which may be used to build more than just javadocs of Jakarta EE 8;-) is appropriate or is something missing?

I adjusted the artifactId to match what's on MavenCentral. Unless Jakarta EE ".next" came up with a completely different namespace like "ee.jakarta", etc. it should be backward compatible at least in the 2.0 state.

**Comment by m0mus** [comment]
@nigeldeakin is artifact with groupid javax.jms-api deployed from this repository?

**Comment by keilw** [comment]
Good question, because the last time anybody or anything deployed `javax.jms:jms` was 2005: https://search.maven.org/artifact/javax.jms/jms/1.1/jar 
I think I found the other one: https://github.com/eclipse-ee4j/openmq/tree/master/mq/main/javax-jms

So @m0mus @nigeldeakin @dblevins how should this be done in future?
Delete this repository and handle everything in https://github.com/eclipse-ee4j/openmq?

Not sure about the EE4J_8 branch, the one for OpenMQ is still missing an EE4J_8 branch.
However I found something weird there:
```
		<!-- Comment out javax-jms and use version 2.0.1 in maven until we work on next release -->
                <!--module>javax-jms</module-->
```
So while the codebase in OpenMQ seems like the source of truth based on the artifactId, it is not built right now, but requires manual comment-in, I guess that's not how a proper build pipeline and chain should look like? ;-)

**Comment by nigeldeakin** [comment]
(Previous comment has been edited)

**Comment by keilw** [comment]
I think in JSONP it may also be grown historically in a similar way, but e.g. JSONB, please @m0mus correct me, there seems to be a clear separation between [API](https://github.com/eclipse-ee4j/jsonb-api) and its [RI](https://github.com/eclipse-ee4j/yasson)

**Comment by keilw** [comment]
What exactly is still open here?

**Comment by OndroMih** [comment]
This issue seems to be about the initial contribution. I'm closing this since it's too old and the initial contribution is finished.
