### ISSUE TITLE
Merge (original) Messaging specification source

### ISSUE THREAD

**Issue by kwsutter** [jakartaee/messaging#257]
Just an FYI... The original (oracle) JMS Messaging specification source is now available via this CQ: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=21463

Please import/modify/merge it when time allows, hopefully in time for Jakarta EE 9. Thanks!

**Comment by m-reza-rahman** [comment]
If this is still relevant, I would mark this as "good first issue" and "help wanted". We should be able to recruit end users to do this after that.

Reza Rahman
Jakarta EE Ambassador, Author, Blogger, Speaker

Please note views expressed here are my own as an individual community member and do not reflect the views of my employer.

**Comment by OndroMih** [comment]
This isn't relevant anymore, it was done by https://github.com/jakartaee/messaging/commit/27a1ba61e02220f403e73da87156cea00be2b9b7
