### ISSUE TITLE
[spec] Need a What's changed in 3.0 section

### ISSUE THREAD

**Issue by hussainnm** [jakartaee/messaging#285]
The specification document currently has no mention of what has changed between Jakarta Messaging 2.0 and 3.0 release. A basic write-up of namespace change from javax to jakarta is required

**Comment by m-reza-rahman** [comment]
This looks sensible. I would mark this as "good first issue" and "help wanted". We should be able to recruit end users to do this after that.

Reza Rahman
Jakarta EE Ambassador, Author, Blogger, Speaker

Please note views expressed here are my own as an individual community member and do not reflect the views of my employer.

**Comment by OndroMih** [comment]
Fixed for 3.0 by https://github.com/jakartaee/messaging/pull/314
