### ISSUE TITLE
TCK test for @JMSConnectionFactoryDefinition as a repeatable annotation

### ISSUE THREAD

**Issue by dblevins** [jakartaee/messaging#299]
After PR #298 for issue #151 we need to add a test to the TCK that uses the `@JMSConnectionFactoryDefinition` annotation repeatably and verifies the vendor supports it. For that we can most likely find the test that uses `@JMSConnectionFactoryDefinitions` and copy/modify it.  Hopefully there is a test that uses that annotation meaningfully.

**Comment by OndroMih** [comment]
Fixed by https://github.com/eclipse-ee4j/jakartaee-tck/pull/851. Some work still to do to improve the TCK based on the comments on the PR, so I leave this issue open to track it.
