### ISSUE TITLE
TCK test for @JMSDestinationDefinition as a repeatable annotation

### ISSUE THREAD

**Issue by dblevins** [jakartaee/messaging#300]
After PR #298 for issue #151 we need to add a test to the TCK that uses the `@JMSDestinationDefinition` annotation repeatably and verifies the vendor supports it. For that we can most likely find the test that uses `@JMSDestinationDefinitions` and copy/modify it.  Hopefully there is a test that uses that annotation meaningfully.

**Comment by OndroMih** [comment]
Fixed by https://github.com/eclipse-ee4j/jakartaee-tck/pull/851.
