### ISSUE TITLE
Finalize the Jakarta Messaging 3.1 Release

### ISSUE THREAD

**Issue by jeanouii** [jakartaee/messaging#323]
## Please complete these steps to finalize the release:

- [ ] promotes api staging release promotes the specification api jars to maven central. An example release job script can be found here https://wiki.eclipse.org/MavenReleaseScript.
- [ ] go through the merged jakarta.ee specification website page to verify all the links are valid.
- [ ] if XML Schemas are published on https://jakarta.ee/schemas, send a PR to update the status from Draft to Final.
- [ ] approve the compatibility request.
- [ ] The compatible implementation project/vendor MUST send an email to [tck@eclipse.org](mailto:tck@eclipse.org) for approval of the compatible implementation for trademark usage.
- [ ] merge any final release branch as appropriate for the branch management for the project.

**Comment by pzygielo** [comment]
Hello Messaging Team,

May I ask to have api artifact released to Central, please?

**Comment by OndroMih** [comment]
Hi @pzygielo, it's released now: https://repo.maven.apache.org/maven2/jakarta/jms/jakarta.jms-api/3.1.0/

**Comment by pzygielo** [comment]
:tada: - @OndroMih - thank you!

**Comment by OndroMih** [comment]
3.1.0 is released, closing this issue.

**Comment by pzygielo** [comment]
All projects seem to be at 3.1.0-SNAPSHOT on master.
So the branch that 3.1.0 was released from was not merged to master, was it?
It also doesn't look like being pushed here.

**Comment by OndroMih** [comment]
You're right, 3.1.0 wasn't merged to master yet. Jenkins was used to release in a separate branch, so the release branch and tag exist.

**Comment by pzygielo** [comment]
- https://www.eclipse.org/lists/messaging-dev/msg00088.html

**Comment by OndroMih** [comment]
The master branch is now up to date: https://github.com/jakartaee/messaging/pull/339
