### ISSUE TITLE
Compatibility certification request for Eclipse OpenMQ 6.4.0 for Jakarta Messaging 3.1 (of Jakarta EE 10)

### ISSUE THREAD

**Issue by pzygielo** [jakartaee/messaging#329]
* [x]  Organization Name ("Organization") and, if applicable, URL: 
  Eclipse Foundation
* [x]  Product Name, Version and download URL (if applicable):
  [Eclipse OpenMQ 6.4.0](https://github.com/eclipse-ee4j/openmq/releases/download/6.4.0-RELEASE/mq-distribution-6.4.0.zip)
* [x]  Specification Name, Version and download URL: 
  [Jakarta Messaging 3.1](https://jakarta.ee/specifications/messaging/3.1/)
* [x]  TCK Version, digital SHA-256 fingerprint and download URL: 
  [Jakarta Messaging TCK 3.1.0](http://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/promoted/eftl/jakarta-messaging-tck-3.1.0.zip), SHA-256: 3ea9e4d9eb6c7ebd2f60f920c1e76ea2e2928540b0eee78120a18453d5851644
* [x]  Public URL of TCK Results Summary:
  https://github.com/eclipse-ee4j/openmq/releases/download/6.4.0-RELEASE/tck-summary.txt
* [x]  Any Additional Specification Certification Requirements:
  None 
* [x]  Java runtime used to run the implementation:
  [OpenJDK 11.0.2+9](https://ci.eclipse.org/openmq/job/2_openmq-run-tck-against-staged-build/45/)
* [x]  Summary of the information for the certification environment, operating system, cloud, ...: 
  * TCK executed using the OpenMQ Jenkins instance, the [2_openmq-run-tck-against-staged-build](https://ci.eclipse.org/openmq/job/2_openmq-run-tck-against-staged-build/45/) job
* [x]  By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
* [x]  By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by pzygielo** [comment]
On March 14 (14 days ago) I've emailed tck@eclipse.org with _Compatibility certification request for Eclipse OpenMQ 6.4.0 for Jakarta Messaging 3.1_.
I've got reply: _[...] you may consider that requirement complete_ (some conditions apply).

May I ask to have this issue checked if anything is missing or changes are required here and have this processed (labelled, approved/rejected), please?

@dblevins 


-----

https://jakarta.ee/committees/specification/tckprocess/
> Certification Resolution
>
> As noted, certification requests do not in themselves grant rights to use the Jakarta EE logo. Approval that the TCK requirements have been met is a prerequisite for obtaining Jakarta EE logo usage for profile certification. The required approval processes is:
>
> -   Approval by lazy consensus after a period of two weeks (14 days)
>
> -   Approval by a majority vote of the specification project as soon as it happens.
        The sum of the +1/-1 votes must be greater than 50% of the specification project committers.
>
> -   Approval by any top-level specification project lead at any time

**Comment by ivargrimstad** [comment]
LGTM +1
